@extends('layouts.admin')

@section('title', 'Saved Reports')
@section('subtitle', 'All generated reports are saved here')

@section('content')
<div class="space-y-6">
    <!-- Stats -->
    <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
        <div class="bg-white rounded-xl shadow-sm p-4 border-l-4 border-blue-500">
            <p class="text-gray-500 text-xs">Total Reports</p>
            <p class="text-2xl font-bold">{{ $stats['total'] }}</p>
        </div>
        <div class="bg-white rounded-xl shadow-sm p-4 border-l-4 border-green-500">
            <p class="text-gray-500 text-xs">Total Size</p>
            <p class="text-2xl font-bold">{{ round($stats['total_size'] / 1024, 2) }} KB</p>
        </div>
        <div class="bg-white rounded-xl shadow-sm p-4 border-l-4 border-purple-500">
            <p class="text-gray-500 text-xs">Report Types</p>
            <p class="text-2xl font-bold">{{ $stats['by_type']->count() }}</p>
        </div>
    </div>

    <!-- Reports Table -->
    <div class="bg-white rounded-xl shadow-sm overflow-hidden">
        <div class="px-6 py-4 border-b bg-gray-50">
            <h3 class="text-lg font-semibold">📁 Saved Reports</h3>
        </div>
        
        <div class="overflow-x-auto">
            <table class="w-full">
                <thead class="bg-gray-50 border-b">
                    <tr>
                        <th class="px-4 py-3 text-left text-xs">ID</th>
                        <th class="px-4 py-3 text-left text-xs">Report Type</th>
                        <th class="px-4 py-3 text-left text-xs">Title</th>
                        <th class="px-4 py-3 text-left text-xs">File Name</th>
                        <th class="px-4 py-3 text-left text-xs">Size</th>
                        <th class="px-4 py-3 text-left text-xs">Generated By</th>
                        <th class="px-4 py-3 text-left text-xs">Date</th>
                        <th class="px-4 py-3 text-center text-xs">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse($reports as $report)
                    <tr class="border-b hover:bg-gray-50">
                        <td class="px-4 py-3">#{{ $report->id }}</td>
                        <td class="px-4 py-3">
                            <span class="px-2 py-1 text-xs rounded-full 
                                @if($report->report_type == 'booking') bg-blue-100 text-blue-700
                                @elseif($report->report_type == 'full_delivery') bg-green-100 text-green-700
                                @elseif($report->report_type == 'partial_delivery') bg-orange-100 text-orange-700
                                @elseif($report->report_type == 'urgent') bg-red-100 text-red-700
                                @else bg-yellow-100 text-yellow-700 @endif">
                                {{ str_replace('_', ' ', ucfirst($report->report_type)) }}
                            </span>
                        </td>
                        <td class="px-4 py-3">{{ $report->title }}</td>
                        <td class="px-4 py-3 text-sm">{{ $report->file_name }}</td>
                        <td class="px-4 py-3">{{ round($report->file_size / 1024, 2) }} KB</td>
                        <td class="px-4 py-3">{{ $report->generator->name ?? 'Admin' }}</td>
                        <td class="px-4 py-3">{{ \Carbon\Carbon::parse($report->created_at)->format('d-m-Y H:i') }}</td>
                        <td class="px-4 py-3 text-center">
                            <div class="flex gap-2 justify-center">
                                <a href="{{ route('admin.reports.view-saved', $report->id) }}" target="_blank" class="text-blue-600 hover:text-blue-800" title="View">
                                    <i class="ri-eye-line text-xl"></i>
                                </a>
                                <a href="{{ route('admin.reports.download-saved', $report->id) }}" class="text-green-600 hover:text-green-800" title="Download">
                                    <i class="ri-download-line text-xl"></i>
                                </a>
                                <button onclick="deleteReport({{ $report->id }})" class="text-red-600 hover:text-red-800" title="Delete">
                                    <i class="ri-delete-bin-line text-xl"></i>
                                </button>
                            </div>
                        </td>
                    </tr>
                    @empty
                    <tr>
                        <td colspan="8" class="px-4 py-8 text-center text-gray-500">
                            <i class="ri-file-copy-line text-4xl mb-2 block"></i>
                            No saved reports found
                            <p class="text-sm mt-1">Generate reports to save them here</p>
                        </td>
                    </tr>
                    @endforelse
                </tbody>
            </table>
        </div>
        
        @if(method_exists($reports, 'links'))
        <div class="px-4 py-3 border-t">
            {{ $reports->links() }}
        </div>
        @endif
    </div>
</div>

<script>
function deleteReport(id) {
    if(confirm('Are you sure you want to delete this report?')) {
        $.ajax({
            url: '/admin/reports/delete-saved/' + id,
            method: 'DELETE',
            data: { _token: '{{ csrf_token() }}' },
            success: function(response) {
                if(response.success) {
                    alert('Report deleted successfully');
                    location.reload();
                } else {
                    alert('Error deleting report');
                }
            }
        });
    }
}
</script>
@endsection